#!/usr/bin/env bash
#
# A generic test suite for chat server implementations in any language.
#
# It runs the test scripts in the test/ directory using test/bin/testhelper.py

set -e

FILE_DIR=tmp_testfiles
TEST_DB=tmp_testdb.sqlite3

if [[ $# -ne 1 ]]; then
    echo "Usage: ./testclient <path to server executable>"
    exit 1
fi

# Kill the background server process on exit.
# Courtesy of https://stackoverflow.com/questions/360201/
trap 'kill $(jobs -p)' EXIT

rm -rf "$FILE_DIR" "$TEST_DB"

mkdir "$FILE_DIR"
python3 test/createdb.py "$TEST_DB"

# Start the server in the background.
$1 -f "$FILE_DIR" -d "$TEST_DB" &

# Wait for the server to boot up.
sleep 0.2

# Run the test script.
python3 test/test_all.py

rm -rf "$FILE_DIR" "$TEST_DB"
